wx:
  APPID: wxc519bd2bc20412d3
  APPSECRET: f3ec125001bd0a16f8736a57988fb9b2
  tocken: ASDASDxcasdasd123ASD

  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET


server:
  port: 8908
  context-path: /weixin

spring:
  datasource:
    url: jdbc:mysql://192.168.1.234:3306/cubic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ;Zi;)r3bq(ss,;ds
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false